### PR TITLE
Add Shop and Cart to Product Modal

### PR DESCRIPTION
**Pull request by Simpcyclassy**

### CODE REVIEW

**Comment by enyeInc** [comment]
@Simpcyclassy This is good to be merged down, can you add an image of your work to this PR?

**Comment by Simpcyclassy** [comment]
> @Simpcyclassy This is good to be merged down, can you add an image of your work to this PR?

Alright.

**Comment by Simpcyclassy** [comment]
image

**Review by EngrEric — APPROVED** [review]
looks good to me

**Comment by joshuaobinna** [comment]
looks good to me

**Review by enyeInc — APPROVED** [review]

**Pull request merged**
