### PR TITLE
Fix/josh/re work product list modal

### PR DESCRIPTION
**Pull request by joshuaobinna**

### CODE REVIEW

**Comment by Way2nnadi** [comment]
@joshuaobinna Explain to me what it is that your code does? and then explain to me what it was that you were supposed to do as part of the clean up efforts?

**Comment by Way2nnadi** [comment]
@joshuaobinna also your build is failing, click on the details to figure out why

**Comment by joshuaobinna** [comment]
The modal does not do anything different from what it already does, it is just a code clean up. The modal component should be on the same level as the card, and only the data needed by the modal should be passed to it

**Comment by enyeInc** [comment]
@joshuaobinna can you show me where you are doing that in this PR that you submitted?

**Review by enyeInc — CHANGES_REQUESTED** [review]
this code is not fit to be merged

**Review by EngrEric — COMMENTED** [review]
This PR will be closed given that its not performing any update

**Pull request closed without merging**
